name: Static analysis

on:
  push:
    branch:
      - develop
      - master
      - main

  pull_request_target:
    branch:
      - "*"

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@make-it-work-on-fork
      with:
        verbose: true
        exclude_dir: lib
        cmake_args: -DCMAKE_BUILD_TYPE=Debug
