name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Upload Documentation to Wiki
        uses: JacobDomagala/TestAction@master
        with:
          github_personal_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          github_token: ${{ github.token }}
          repo: JacobDomagala/DGame
          workflow: Ubuntu.yml
          filename: build_times.png
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          docker_repository: jdomagala/test-repo

