name: Static analysis

on: [pull_request]

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@19-fix-issue-with-single-line-files
      with:
        exclude_dir: lib
        cmake_args: -DCMAKE_BUILD_TYPE=Debug
