name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Build & Push
        uses: jerray/publish-docker-action@master
        with:
            # Docker registry username
            username: ${{ secrets.DOCKER_USERNAME }}
            # Docker registry password
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: jdomagala/test-repo
