name: Test_Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - shell: bash
      run: |
        echo RUN_ID = $GITHUB_RUN_ID
        curl \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/JacobDomagala/TestRepo/actions/runs/$GITHUB_RUN_ID/timing

