name: Static analysis

on: [pull_request]

jobs:
  static analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
